name: Ruff Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "src/**"
      - "scripts/**"
      - "bot.py"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Ruff Lint
        uses: chartboost/ruff-action@v1
